<a href="https://colab.research.google.com/github/PixelKnocks00/Codes/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# ------------------------->Conversion from python structures
import numpy as np
# my_num=np.array([1,2,5,7,6])
# # print(my_num[0])
# my_num2=np.array([12,32,44,54],np.int16)  # The np.int etc tells that how much memory we need in pour program
# # print(my_num2*5)
# my_num3=np.array([[12,32,44,54]],np.int16)  # Now its a 2d array with two brackets
# print(my_num3.shape) #It tells the shape of yr 2d array like how much col and ros it has
# my_num3.dtype#It tells the amount of memory we are giving
# my_num3[0,3]=45#changes the element
# # print(my_num3)
# my_num4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# print(my_num4)
# print(my_num4.shape)
# my_num4.dtype
# ------------------------>Some array creation methods
# zer=np.zeros((2,5)) #It will add zeroes on 2 rows and 5 columns on the scrren
# zer
# arr=np.arange(8,20)#It will generate numbers from 8 to 20
# print(arr)
# arr=np.arange(1,8+1).reshape(4,2)#The reshape will change the view to 4 rows , 2 colums
# print(arr)
x=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int8)
# arr=x.sum(axis=0)
# print(arr)
# conv_2_1d=x.flatten()
# print(conv_2_1d)
# for items in x.flat:
#   print(items)
# print(x.T)
# print(x.ndim) # Tells the total dimensions of array
# print(x.size)# Tells the total no of elements in array
# print(x.nbytes)# Tells the total no of bytes consumed
print(x)
print(x.T)
print(x.ndim)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
2


🎀 There are axis in numpy or array .

 ---> The 0 axis means sum of **rows** (all the rows) seperately<br>

 ---> The 1 axis means sum of **columns** (all the columnss) seperately<br>

🎀 Flat : It is used to convert 2d array back to 1d <br

---> flatern is used to convert or print it on a single in horizontal

---> using for loop eg (for items in x.flat) prints it in vertical line

🎀 x.T : It will tranpose the array(rows to columns and columns to rows)

🎀 x.ndim:Tells the dimensions of the array

🎀 x.size:Tells the total no of elements in array

🎀 x.nbytes:Tells the amount of bytes consumed by the compiler

